-- 코드를 입력하세요
# SELECT *
# FROM ONLINE_SALE
# GROUP BY SALES_DATE, USER_ID

SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(*) AS USERS
FROM (
    SELECT *
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID) AS sub
LEFT JOIN USER_INFO
USING(USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY 
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    GENDER
ORDER BY YEAR, MONTH, GENDER;