-- 코드를 입력하세요
WITH sub AS (
    SELECT
        FOOD_TYPE, 
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE )
    
SELECT 
    s.FOOD_TYPE,
    m.REST_ID,
    m.REST_NAME,
    m.FAVORITES
FROM sub AS s
LEFT JOIN REST_INFO AS m
ON s.MAX_FAVORITES = m.FAVORITES
    AND s.FOOD_TYPE = m.FOOD_TYPE
ORDER BY s.FOOD_TYPE DESC;
     