-- 코드를 입력하세요
-- WITH 절
/*
WITH sub AS (
    SELECT 
        FOOD_TYPE, 
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE )
    
SELECT 
    s.FOOD_TYPE,
    m.REST_ID,
    m.REST_NAME,
    m.FAVORITES
FROM REST_INFO AS m
INNER JOIN sub AS s
ON s.MAX_FAVORITES = m.FAVORITES
    AND s.FOOD_TYPE = m.FOOD_TYPE
ORDER BY s.FOOD_TYPE DESC;
*/

-- WHERE절 IN 이하 서브쿼리 이용
SELECT 
    FOOD_TYPE,
    REST_ID,
    REST_NAME, 
    FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    )
GROUP BY FOOD_TYPE 
ORDER BY FOOD_TYPE DESC;