-- 코드를 입력하세요
-- 2023년 3월 - 
-- ONLINE / OFFLINE의 판매날짜, 상품ID, 유저ID, 판매량
-- OFFLINE의 USER_ID는 NULL
-- 판매일, 상품ID, 유저ID 오름차순
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION ALL
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    CASE WHEN OFFLINE_SALE_ID IS NOT NULL THEN NULL END AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;