## 조회수가 가장 높은 중고거래 게시물 -> 첨부파일 경로

-- 코드를 입력하세요
# SELECT *
SELECT CONCAT("/home/grep/src/", BOARD_ID, "/", FILE_ID,FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, VIEWS 
    FROM USED_GOODS_BOARD 
    GROUP BY BOARD_ID 
    ORDER BY VIEWS DESC 
    LIMIT 1) AS a
LEFT JOIN USED_GOODS_FILE AS b
USING (BOARD_ID)
ORDER BY b.FILE_ID DESC;

# SELECT *
# FROM USED_GOODS_FILE
# ORDER BY BOARD_ID


