-- 코드를 입력하세요
SELECT 
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS s
LEFT JOIN BOOK AS b
USING (BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%m') = '01'
GROUP BY CATEGORY
ORDER BY CATEGORY;