-- 코드를 입력하세요
SELECT
    p.PRODUCT_CODE,
    p.PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT as p 
LEFT JOIN OFFLINE_SALE as os
USING (PRODUCT_ID)
GROUP BY p.PRODUCT_CODE
ORDER BY 
    SALES DESC,
    p.PRODUCT_CODE;
