-- 코드를 입력하세요
-- 생산일자 2022년 5월
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER as fo
LEFT JOIN FOOD_PRODUCT as fp
USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC,
    PRODUCT_ID;