-- APNT_YMD = '2022-04-13'
-- APNT_CNCL_YN == 'N'

-- 코드를 입력하세요
SELECT 
    a.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    d.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD    
FROM APPOINTMENT AS a
LEFT JOIN DOCTOR AS d
ON a.MDDR_ID = d.DR_ID
LEFT JOIN PATIENT AS p
ON a.PT_NO = p.PT_NO
WHERE DATE(a.APNT_YMD) = '2022-04-13' AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD
    