/* 
2022년 5월 - WEHRE
예약 Y - WHERE
환자수 - COUNT
진료과 코드별 - GROUP BY
*/
-- 코드를 입력하세요
SELECT 
    MCDP_CD AS '진료과코드', 
    COUNT(MCDP_CD) AS '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05' 
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_YMD), MCDP_CD;